//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_company.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text.RegularExpressions;

    public partial class CarSet : IDataErrorInfo
    {
        public int? ObjectId { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public int? Year { get; set; }
        public string VinNumber { get; set; }
        public string Engine { get; set; }
        public int Policy_PolicyId { get; set; }
    
        public virtual PolicySet PolicySet { get; set; }

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string result = string.Empty;
                switch (columnName)
                {
                    case "Brand":
                        {
                            if (string.IsNullOrEmpty(Brand))
                            {
                                result = "Brand is required!";
                                break;
                            }

                            if (!Regex.IsMatch(Brand, @"^[A-Za-zøüÊÒÛ≥ÍπúØè∆•å £”—]+$"))
                                result = "Only letters!";

                            break;
                        }
                    case "Year":
                        {
                            if (Year == null)
                            {
                                result = "Year is required!";
                                break;
                            }
                            
                            if (Year < 1950 || Year > System.DateTime.Now.Year)
                                result = "Wrong year!";
                            break;
                        }
                    case "VinNumber":
                        {
                            if (string.IsNullOrEmpty(VinNumber))
                            {
                                result = "VIN number is required!";
                                break;
                            }

                            if (!Regex.IsMatch(VinNumber, @"^[\p{L}\p{N}]+$"))
                                result = "Only letters and numbers!";

                            break;
                        }
                    case "Engine":
                        {
                            if (string.IsNullOrEmpty(Engine))
                            {
                                result = "Emgine is required!";
                                break;
                            }

                            if (!Regex.IsMatch(Engine, @"^[\p{L}\p{N}]+$"))
                                result = "Only letters and numbers!";

                            break;
                        }
                    case "Type":
                        {
                            if (Type == null)
                                result = "Choose type!";

                            break;
                        }
                };
                return result;
            }
        }
    }
}
