//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_company.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text.RegularExpressions;

    public partial class HouseSet : IDataErrorInfo
    {
        public int ObjectId { get; set; }
        public int? Year { get; set; }
        public int? Size { get; set; }
        public string Type { get; set; }
        public int Policy_PolicyId { get; set; }
    
        public virtual PolicySet PolicySet { get; set; }
        public virtual AdressSet AdressSet { get; set; }

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string result = string.Empty;
                switch (columnName)
                {
                    case "Year":
                        {
                            if (Year == null)
                            {
                                result = "Year is required!";
                                break;
                            }

                            if (Year < 1900 || Year > System.DateTime.Now.Year)
                                result = "Wrong year!";
                            break;
                        }
                    case "Size":
                        {
                            if (Size == null)
                            {
                                result = "Size is required!";
                                break;
                            }

                            if (Size < 20 || Size > 2000)
                                result = "Wrong size!";
                            break;
                        }
                    case "Type":
                        {
                            if (Type == null)
                                result = "Choose type!";

                            break;
                        }
                };
                return result;
            }
        }
    }
}
